all:
  hosts:
    mei:
      ansible_host: 127.0.0.1
      ansible_port: 2221
      ansible_user: ansible
      ansible_ssh_private_key_file: ./ssh/id_ed25519


  vars:
    ollama_models: qwen3.5:0.8b # Change or add others depending on your HW
    homelab_user: another # Change based on preference
    homelab_user_password: "$6$pEPHW2VIA0mL9e4u$z5TQV9tBCRRm2k43ciNi3iqjQK.jHs7iUZDvRTyuONlVglJqtlCx4rMa7fKC3XQBOZxnHQSLfAkXcIu.2.2dS0"  # Change this password to a secure one - it's just a changeme password. To generate a passwd suitable for linux, use openssl passwd -6
    osiris_repo: "https://github.com/simplifaisoul/osiris.git"
    osiris_path: "/home/{{ homelab_user }}/OSINT/OSIRIS"
    osiris_port: 3200 # Change if being used
    pixelmon_op: AnotherOne661 # Change to Admin username
    pixelmon_memory: "2G" # Recommended 8-12GB
    pixelmon_path: /minecraft/pixelmon
